env=EDITOR,nvim
env=VISUAL,nvim
env=TERMINAL,kitty

exec-once=waybar
exec-once=awww-daemon
exec-once=/usr/lib/xdg-desktop-portal-wlr
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &
exec-once=wl-paste --type text --watch cliphist --max-items 50 store 
exec-once=mako &
exec=~/.config/fuzzel/notif-logger.sh &

# Monitor config - monitorrule=name:Values,Parameter:Values,Parameter:Values
monitorrule=make:HKC OVERSEAS LIMITED,model:0x36BB,width:1920,height:1200,refresh:59.988998,x:0,y:0,scale:1.20
xwayland_ignore_scale=1

# Trackpad and keyboard
tap_to_click=1
tap_and_drag=1
trackpad_natural_scrolling=1
trackpad_accel_speed=0.5
trackpad_disable_while_typing=0
swipe_min_threshold=1

mouse_accel_speed=0.5

xwayland_persistence=1
syncobj_enable=1
allow_lock_transparent=1
allow_shortcuts_inhibit=1

sloppyfocus=1
warpcursor=1
cursor_hide_timeout=5
drag_tile_to_tile=1

idleinhibit_ignore_visible=1
idleinhibit_when_fullscreen=1

